# Generated by Django 4.2.9 on 2026-04-09 09:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор ВУЗа')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Преподаватель')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('academic_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Научное звание')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номер / название')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Вместимость')),
                ('room_type', models.CharField(choices=[('lecture', 'Лекционная'), ('seminar', 'Семинарская'), ('comp', 'Компьютерный класс'), ('special', 'Специализированная')], default='seminar', max_length=20, verbose_name='Тип аудитории')),
                ('low_priority', models.BooleanField(default=False, help_text='Использовать только если нет других подходящих аудиторий', verbose_name='Низкий приоритет')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: ПМИ-301', max_length=100, verbose_name='Название группы')),
                ('students', models.PositiveSmallIntegerField(default=25, verbose_name='Количество студентов')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('difficulty_points', models.PositiveSmallIntegerField(default=1, help_text='1 — лёгкий, 5 — очень сложный', verbose_name='Сложность (1–5)')),
                ('pairs_per_semester', models.PositiveSmallIntegerField(default=18, verbose_name='Пар в семестре')),
                ('semester', models.PositiveSmallIntegerField(default=1, verbose_name='Семестр')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель (основной)')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название университета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.CreateModel(
            name='UniversitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_weeks', models.PositiveSmallIntegerField(default=18, verbose_name='Недель в семестре')),
                ('max_pairs_per_day', models.PositiveSmallIntegerField(default=6, verbose_name='Макс. пар в день')),
                ('slot_times', models.JSONField(blank=True, default=dict, help_text='{"1":"08:30","2":"10:15","3":"12:00","4":"13:45","5":"15:30","6":"17:15"}', verbose_name='Времена пар')),
                ('solver_weights', models.JSONField(blank=True, default=dict, help_text='Оставьте пустым для значений по умолчанию', verbose_name='Веса солвера')),
                ('days', models.JSONField(blank=True, default=list, help_text='["Пн","Вт","Ср","Чт","Пт","Сб"]', verbose_name='Рабочие дни')),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Настройки расписания',
                'verbose_name_plural': 'Настройки расписания',
            },
        ),
        migrations.CreateModel(
            name='TeacherPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_lessons_per_day', models.PositiveSmallIntegerField(default=4, verbose_name='Макс. пар в день')),
                ('max_consecutive_lessons', models.PositiveSmallIntegerField(default=2, verbose_name='Макс. пар подряд')),
                ('blocked_slots', models.JSONField(blank=True, default=list, verbose_name='Заблокированные слоты')),
                ('preferred_slots', models.JSONField(blank=True, default=list, verbose_name='Предпочтительные слоты')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Пожелания преподавателя',
                'verbose_name_plural': 'Пожелания преподавателей',
            },
        ),
        migrations.CreateModel(
            name='SubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lecture', 'Лекция'), ('seminar', 'Семинар'), ('comp', 'Компьютерный класс')], default='lecture', max_length=20, verbose_name='Вид занятия')),
                ('room_type', models.CharField(choices=[('lecture', 'Лекционная'), ('seminar', 'Семинарская'), ('comp', 'Компьютерный класс'), ('special', 'Специализированная')], default='seminar', max_length=20, verbose_name='Тип аудитории')),
                ('total_pairs', models.PositiveSmallIntegerField(default=18, verbose_name='Пар за семестр')),
                ('per_group', models.BooleanField(default=False, help_text='Преподаватель ведёт занятие отдельно с каждой группой', verbose_name='Отдельно для каждой группы')),
                ('simultaneous', models.BooleanField(default=False, help_text='Подгруппы занимаются в одно время в разных аудиториях', verbose_name='Одновременно (подгруппы)')),
                ('subgroup_id', models.CharField(blank=True, help_text='Заполнить если это одна из параллельных подгрупп', max_length=50, verbose_name='ID подгруппы')),
                ('min_lectures_before_seminars', models.PositiveSmallIntegerField(default=0, verbose_name='Мин. лекций перед семинарами')),
                ('lecture_to_seminar_ratio', models.FloatField(default=0.5, help_text='0.5 = на 1 лекцию 2 семинара', verbose_name='Соотношение лекция/семинар')),
                ('fixed_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom', verbose_name='Фиксированная аудитория')),
                ('groups', models.ManyToManyField(blank=True, to='core.group', verbose_name='Группы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_configs', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Конфигурация предмета',
                'verbose_name_plural': 'Конфигурации предметов',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.university', verbose_name='Университет'),
        ),
        migrations.CreateModel(
            name='SemesterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week', models.PositiveSmallIntegerField(default=0, verbose_name='Текущая неделя')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя генерация')),
                ('remaining', models.JSONField(default=dict, verbose_name='Остаток пар')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_states', to='core.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Состояние семестра',
                'verbose_name_plural': 'Состояния семестра',
            },
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Инвайт-ссылка',
                'verbose_name_plural': 'Инвайт-ссылки',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='core.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.university', verbose_name='Университет'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='Университет'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота')], verbose_name='День недели')),
                ('slot_number', models.PositiveSmallIntegerField(help_text='1=08:30, 2=10:15, 3=12:00, 4=13:45, 5=15:30, 6=17:15', verbose_name='Номер пары')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная'), ('seminar', 'Семинар'), ('online', 'Онлайн')], default='lecture', max_length=20, verbose_name='Тип занятия')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('week_number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер недели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='core.classroom', verbose_name='Аудитория')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='core.course', verbose_name='Курс')),
                ('groups', models.ManyToManyField(blank=True, related_name='schedule_entries', to='core.group', verbose_name='Группы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='core.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='core.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Запись расписания',
                'verbose_name_plural': 'Расписание',
                'ordering': ['weekday', 'slot_number'],
                'unique_together': {('teacher', 'weekday', 'slot_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('direction', 'number')},
        ),
    ]
