# Generated by Django 4.2.9 on 2026-04-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Семестр'),
        ),
    ]
