# Generated by Django 4.2.9 on 2026-04-04 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_academic_title_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номер / название аудитории')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Вместимость')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.university')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер курса')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_lessons_per_day', models.PositiveSmallIntegerField(default=4, verbose_name='Макс. пар в день')),
                ('max_consecutive_lessons', models.PositiveSmallIntegerField(default=2, verbose_name='Макс. пар подряд')),
                ('blocked_slots', models.JSONField(blank=True, default=list, verbose_name='Заблокированные слоты')),
                ('preferred_slots', models.JSONField(blank=True, default=list, verbose_name='Предпочтительные слоты')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('difficulty_points', models.PositiveSmallIntegerField(default=1, help_text='1 — лёгкий, 5 — очень сложный', verbose_name='Сложность (баллы)')),
                ('hours_per_semester', models.PositiveSmallIntegerField(default=36, verbose_name='Часов в семестре')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.university')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='core.university')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.direction'),
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота')], verbose_name='День недели')),
                ('slot_number', models.PositiveSmallIntegerField(help_text='1=08:30, 2=10:15, 3=12:00, 4=13:45, 5=15:30, 6=17:15', verbose_name='Номер пары')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная'), ('seminar', 'Семинар'), ('online', 'Онлайн')], default='lecture', max_length=20, verbose_name='Тип занятия')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='core.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='core.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='core.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='core.university')),
            ],
            options={
                'ordering': ['weekday', 'slot_number'],
                'unique_together': {('teacher', 'weekday', 'slot_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('direction', 'number')},
        ),
    ]
