# Generated by Django 4.2.9 on 2026-04-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер недели'),
        ),
    ]
