# Generated by Django 4.2.9 on 2026-04-09 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='invitelink',
            options={'verbose_name': 'Инвайт-ссылка', 'verbose_name_plural': 'Инвайт-ссылки'},
        ),
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'ordering': ['weekday', 'slot_number'], 'verbose_name': 'Запись расписания', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacherpreference',
            options={'verbose_name': 'Пожелания преподавателя', 'verbose_name_plural': 'Пожелания преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Университет', 'verbose_name_plural': 'Университеты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='low_priority',
            field=models.BooleanField(default=False, help_text='Использовать только если нет других подходящих аудиторий', verbose_name='Низкий приоритет'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Лекционная'), ('seminar', 'Семинарская'), ('comp', 'Компьютерный класс'), ('special', 'Специализированная')], default='seminar', max_length=20, verbose_name='Тип аудитории'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='Количество студентов'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='schedule_entries', to='core.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Номер / название'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.university', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='core.university', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='core.classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='core.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='core.university', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='difficulty_points',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 — лёгкий, 5 — очень сложный', verbose_name='Сложность (1–5)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель (основной)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.university', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='teacherpreference',
            name='teacher',
            field=models.OneToOneField(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='Университет'),
        ),
        migrations.CreateModel(
            name='UniversitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_weeks', models.PositiveSmallIntegerField(default=18, verbose_name='Недель в семестре')),
                ('max_pairs_per_day', models.PositiveSmallIntegerField(default=6, verbose_name='Макс. пар в день')),
                ('slot_times', models.JSONField(blank=True, default=dict, help_text='{"1":"08:30","2":"10:15","3":"12:00","4":"13:45","5":"15:30","6":"17:15"}', verbose_name='Времена пар')),
                ('solver_weights', models.JSONField(blank=True, default=dict, help_text='Оставьте пустым для значений по умолчанию', verbose_name='Веса солвера')),
                ('days', models.JSONField(blank=True, default=list, help_text='["Пн","Вт","Ср","Чт","Пт","Сб"]', verbose_name='Рабочие дни')),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Настройки расписания',
                'verbose_name_plural': 'Настройки расписания',
            },
        ),
        migrations.CreateModel(
            name='SubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lecture', 'Лекция'), ('seminar', 'Семинар'), ('comp', 'Компьютерный класс')], default='lecture', max_length=20, verbose_name='Вид занятия')),
                ('room_type', models.CharField(choices=[('lecture', 'Лекционная'), ('seminar', 'Семинарская'), ('comp', 'Компьютерный класс'), ('special', 'Специализированная')], default='seminar', max_length=20, verbose_name='Тип аудитории')),
                ('total_pairs', models.PositiveSmallIntegerField(default=18, verbose_name='Пар за семестр')),
                ('per_group', models.BooleanField(default=False, help_text='Преподаватель ведёт занятие отдельно с каждой группой', verbose_name='Отдельно для каждой группы')),
                ('simultaneous', models.BooleanField(default=False, help_text='Подгруппы занимаются в одно время в разных аудиториях', verbose_name='Одновременно (подгруппы)')),
                ('subgroup_id', models.CharField(blank=True, help_text='Заполнить если это одна из параллельных подгрупп', max_length=50, verbose_name='ID подгруппы')),
                ('min_lectures_before_seminars', models.PositiveSmallIntegerField(default=0, verbose_name='Мин. лекций перед семинарами')),
                ('lecture_to_seminar_ratio', models.FloatField(default=0.5, help_text='0.5 = на 1 лекцию 2 семинара', verbose_name='Соотношение лекция/семинар')),
                ('fixed_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom', verbose_name='Фиксированная аудитория')),
                ('groups', models.ManyToManyField(blank=True, to='core.group', verbose_name='Группы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_configs', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Конфигурация предмета',
                'verbose_name_plural': 'Конфигурации предметов',
            },
        ),
        migrations.CreateModel(
            name='SemesterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week', models.PositiveSmallIntegerField(default=0, verbose_name='Текущая неделя')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя генерация')),
                ('remaining', models.JSONField(default=dict, verbose_name='Остаток пар')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_states', to='core.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Состояние семестра',
                'verbose_name_plural': 'Состояния семестра',
            },
        ),
    ]
